id: CFD84FE7-D39E-49BD-8E5F-0132B135CDE1
name: ApplicationImplicitGrantFlow
description: |
  'This query searches for this application that can implicitly be granted OAuth 2.0 login authority. 
   Investigate immediately.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1528
  - T1550
query: |
  SenservaPro_CL
  | where ControlName_s == 'ApplicationImplicitGrantFlow'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  