id: 37633A6E-9D1C-40EF-9C00-F0BBB18E3010
name: ApplicationsGroup
description: |
  'This query searches for Senserva Applications-group collection.' 
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1518 
query: |
  SenservaPro_CL
  |where TimeGenerated > ago(1d)
  |where Group_s == 'Applications' 
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  