id: FAB4B0B6-EF51-4326-B99A-F031D59A7E3C
name: ApplicationPasswordCredentialAddedRecently
description: |
  'This query searches for this application has had a Password Credential recently added to it. 
   Validate immediately.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1528
  - T1550
query: |
  SenservaPro_CL
  | where ControlName_s == 'ApplicationPasswordCredentialAddedRecently'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  