id: CB37FCC5-F90F-4217-AEE7-4B95DC3228C5
name: ApplicationPermission
description: |
  'This query searches for permissions are assigned to access a particular set of data needed for operation. 
   Permission can grant users read or write access within an application without an Azure Active Directory role.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1528
query: |
  SenservaPro_CL
  | where ControlName_s == 'ApplicationPermission'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  