id: CDD87DEB-E21F-4F7F-B201-6396D7EDB641
name: ApplicationKeyCredentialAddedRecently
description: |
  'This query searches for this Application has had a certificate credential recently added to it. 
   Validate immediately.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1528
  - T1550
query: |
  SenservaPro_CL
  | where ControlName_s == 'ApplicationKeyCredentialAddedRecently'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  