id: 2841AFAC-295D-4419-9182-94BB1E92383A
name: ConditionalAccessMobileUsersNotRequiredToUseApprovedApplicationsEnabled
description: |
  'This query searches for mobile users are not required to use approved applications is enabled.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1410
  - T1416
  - T1417
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConditionalAccessMobileUsersNotRequiredToUseApprovedApplicationsEnabled'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  