id: 97C9C9A1-0AF8-44E5-A7B4-AA361A8F7487
name: ConditionalAccessBlockedLegacyApplicationsShouldIncludeOffice365
description: |
  'This query searches for Office should block legacy application for conditional access.
   Legacy authentication clients can skip things like MFA and must not be used.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1098
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConditionalAccessBlockedLegacyApplicationsShouldIncludeOffice365'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  