id: 7F17B1ED-9B73-4DA9-BB16-BA1D5343CEE6
name: ConditionalAccessExcludedApplication
description: |
  'This query searches for rule excludes application make sure this is what is required,
   it overrides all else for this app.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1098
  - T1110
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConditionalAccessExcludedApplication'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  