id: F06A89D5-3C6B-423D-89E8-BFD9E0BD73C9
name: ConfigurationStateAccountBannedPasswordListFailed
description: |
  'This query searches for custom banned passwords provide extra protections to the network'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1078
  - T1098
  - T1110
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConfigurationStateAccountBannedPasswordListFailed'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  