id: 3FE6C191-E6B5-4415-AA9D-E3FD4C8130DE
name: ConfigurationTooManyGloblalAdministrators
description: |
  'This query searches for Microsoft recommmeneds 4 or less global administrators.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1078
  - T1087
  - T1098
  - T1136
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConfigurationTooManyGloblalAdministrators'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  