id: 11F8C021-8D36-49C7-A5E3-E0CF91B3FF56
name: ConfigurationNotEnoughGloblalAdministrators
description: |
  'This query searches for Microsoft recommmeneds 4 or less global administrators but more than 1.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1078
  - T1087
  - T1098
  - T1136
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConfigurationNotEnoughGloblalAdministrators'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  