id: AC9C5611-05D6-4B9C-97C7-B9AEF9FC77DF
name: ConfigurationStateAzureADDeletedUsersList
description: |
  'This query searches for Audit the deleted user accounts in your tenant. 
   These Deleted Accounts can still be recovered and used to infiltrate your network.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1078
  - T1087
  - T1098
  - T1136
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConfigurationStateAzureADDeletedUsersList'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  