id: 275B867C-1069-409E-9C7A-34CCDC888CE8
name: ConfigurationStateAzureADCustomRolesInUse
description: |
  'This query searches for Azure AD custom roles can have a custom set of permissions, inlcuding administrator privileges.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1098
  - T1562
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConfigurationStateAzureADCustomRolesInUse'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  