id: 5A35B748-F09D-4BEB-B798-6F01A49973C2
name: ConfigurationStateAzureADFederatedDomainsList
description: |
  'This query searches for Limit the use of Federated Domains when possible. 
   Federated Domains use authentication through a provider that is different than Azure AD.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1482
  - T1484
  - T1562
  - T1606
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConfigurationStateAzureADFederatedDomainsList'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  