id: 37C81D27-BF8B-4899-A3F0-4F2F4B33F757
name: ConfigurationStateAzureADDeletedApplicationsList
description: |
  'This query searches for Audit the Deleted Applications in your tenant. 
   These Deleted Applications can still be recovered and used to infiltrate your network.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1078
  - T1087
  - T1098
  - T1136
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConfigurationStateAzureADDeletedApplicationsList'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  