id: E455C799-336F-4A9B-A043-54DE1B4FEF23
name: ConfigurationStateAzureADContinuousAccessEvaluationInUse
description: |
  'This query searches for Azure AD continuous access evaluation policy is a setting 
   to enforce near real time evaluation of user account changes like password change and account disabling.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1078
  - T1098
  - T1562
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConfigurationStateAzureADContinuousAccessEvaluationInUse'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  