id: DB68F673-6D3A-4C7C-804C-93573EBF7955
name: ConfigurationStateAzureADConnectSyncRunRecently
description: |
  'This query searches for Azure AD Connect should be used to sync your on-premises data to your cloud at least weekly.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1482
  - T1484
  - T1558
  - T1562
  - T1606
query: |
  SenservaPro_CL
  | where ControlName_s == 'ConfigurationStateAzureADConnectSyncRunRecently'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  