id: 867E5073-0C8C-43F1-8E6C-597D0D5D8E68
name: UserApplicationOwner
description: |
  'This query searches for application is owned by this user. Owners play a large role in Azure management.'
severity: Medium
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1098
  - T1098.001
  - T1078
  - T1078.004
  - T1528
query: |
  SenservaPro_CL
  | where ControlName_s == 'UserApplicationOwner'
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: ControlName_s
      - identifier: AadTenantId
        columnName: TenantId
      - identifier: DisplayName
        columnName: Tenant_TenantDisplayName_s 
  - entityType: SecurityGroup
    fieldMappings:
      - identifier: DistinguishedName
        columnName: Group_s
  - entityType: AzureResource
    fieldMappings:
      - identifier: ResourceId
        columnName: SourceSystem 
  